# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه آلرژی')),
                ('substance', models.CharField(max_length=200, verbose_name='ماده حساسیت\u200cزا')),
                ('substance_type', models.CharField(choices=[('Drug', 'دارو'), ('Food', 'غذا'), ('Environment', 'محیطی'), ('Other', 'سایر')], max_length=50, verbose_name='نوع ماده')),
                ('reaction', models.TextField(verbose_name='شرح واکنش')),
                ('severity', models.CharField(choices=[('Mild', 'خفیف'), ('Moderate', 'متوسط'), ('Severe', 'شدید'), ('Life-Threatening', 'تهدید کننده حیات')], max_length=20, verbose_name='شدت')),
                ('verification_status', models.CharField(choices=[('Suspected', 'مشکوک'), ('Confirmed', 'تایید شده'), ('Refuted', 'رد شده')], default='Suspected', max_length=20, verbose_name='وضعیت تایید')),
                ('recorded_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'آلرژی',
                'verbose_name_plural': 'آلرژی\u200cها',
                'ordering': ['-severity', '-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('family_history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه سابقه خانوادگی')),
                ('relation', models.CharField(choices=[('Mother', 'مادر'), ('Father', 'پدر'), ('Sibling', 'خواهر/برادر'), ('MaternalGrandmother', 'مادربزرگ مادری'), ('MaternalGrandfather', 'پدربزرگ مادری'), ('PaternalGrandmother', 'مادربزرگ پدری'), ('PaternalGrandfather', 'پدربزرگ پدری'), ('Aunt', 'عمه/خاله'), ('Uncle', 'عمو/دایی'), ('Child', 'فرزند'), ('Other', 'سایر')], max_length=50, verbose_name='نسبت')),
                ('condition', models.CharField(max_length=200, verbose_name='بیماری یا وضعیت')),
                ('age_of_onset', models.IntegerField(blank=True, null=True, verbose_name='سن شروع بیماری')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='فوت شده')),
                ('cause_of_death', models.CharField(blank=True, max_length=200, null=True, verbose_name='علت فوت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_histories', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه خانوادگی',
                'verbose_name_plural': 'سوابق خانوادگی',
                'ordering': ['relation'],
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immunization_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه واکسیناسیون')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='نام واکسن')),
                ('cvx_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد CVX')),
                ('administered_date', models.DateTimeField(verbose_name='تاریخ تزریق')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل تزریق')),
                ('lot_number', models.CharField(max_length=50, verbose_name='شماره بچ')),
                ('expiration_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('was_refused', models.BooleanField(default=False, verbose_name='امتناع از دریافت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_immunizations', to='providers.provider', verbose_name='تزریق کننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'واکسیناسیون',
                'verbose_name_plural': 'واکسیناسیون\u200cها',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه سابقه')),
                ('history_type', models.CharField(choices=[('Allergy', 'آلرژی'), ('ChronicCondition', 'بیماری مزمن'), ('Surgery', 'جراحی'), ('Medication', 'دارویی'), ('Other', 'سایر')], max_length=50, verbose_name='نوع سابقه')),
                ('description', models.TextField(verbose_name='شرح')),
                ('onset_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع یا تشخیص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه پزشکی',
                'verbose_name_plural': 'سوابق پزشکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه مشکل')),
                ('problem_name', models.CharField(max_length=500, verbose_name='نام مشکل')),
                ('icd10_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ICD-10')),
                ('onset_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='تاریخ حل شدن')),
                ('problem_status', models.CharField(choices=[('Active', 'فعال'), ('Resolved', 'حل شده'), ('Chronic', 'مزمن'), ('Intermittent', 'متناوب')], default='Active', max_length=20, verbose_name='وضعیت مشکل')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'مشکل',
                'verbose_name_plural': 'لیست مشکلات',
                'ordering': ['problem_status', '-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('social_history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه سابقه اجتماعی')),
                ('item_name', models.CharField(choices=[('SmokingStatus', 'وضعیت سیگار'), ('AlcoholUse', 'مصرف الکل'), ('DrugUse', 'مصرف مواد'), ('Occupation', 'شغل'), ('Exercise', 'ورزش'), ('Diet', 'رژیم غذایی'), ('MaritalStatus', 'وضعیت تاهل'), ('LivingSituation', 'وضعیت زندگی'), ('Other', 'سایر')], max_length=50, verbose_name='موضوع')),
                ('item_value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('status', models.CharField(blank=True, choices=[('Current', 'فعلی'), ('Former', 'سابق'), ('Never', 'هرگز')], max_length=20, null=True, verbose_name='وضعیت')),
                ('recorded_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_histories', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه اجتماعی',
                'verbose_name_plural': 'سوابق اجتماعی',
                'ordering': ['item_name', '-recorded_date'],
            },
        ),
    ]
