# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('orders', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('imaging_result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نتیجه تصویربرداری')),
                ('modality', models.CharField(choices=[('X-Ray', 'اشعه ایکس'), ('CT', 'سی\u200cتی اسکن'), ('MRI', 'ام\u200cآر\u200cآی'), ('Ultrasound', 'سونوگرافی'), ('Mammography', 'ماموگرافی'), ('PET', 'پت اسکن'), ('Fluoroscopy', 'فلوروسکوپی'), ('Other', 'سایر')], max_length=20, verbose_name='نوع تصویربرداری')),
                ('body_part', models.CharField(help_text='مثال: Chest, Head, Abdomen', max_length=100, verbose_name='عضو مورد بررسی')),
                ('report_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید گزارش')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='متن گزارش (Findings)')),
                ('impressions', models.TextField(blank=True, null=True, verbose_name='نتیجه\u200cگیری نهایی (Impression)')),
                ('pacs_link', models.URLField(blank=True, help_text='لینک به فایل تصویر در سیستم آرشیو', max_length=255, null=True, verbose_name='لینک تصویر در سیستم PACS')),
                ('imaging_date', models.DateTimeField(verbose_name='تاریخ تصویربرداری')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='encounters.encounter', verbose_name='ویزیت')),
                ('order', models.ForeignKey(limit_choices_to={'order_type': 'Imaging'}, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='orders.order', verbose_name='دستور')),
                ('radiologist', models.ForeignKey(limit_choices_to={'provider_type': 'Radiologist'}, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports', to='providers.provider', verbose_name='رادیولوژیست')),
            ],
            options={
                'verbose_name': 'نتیجه تصویربرداری',
                'verbose_name_plural': 'نتایج تصویربرداری',
                'ordering': ['-imaging_date'],
            },
        ),
    ]
