# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('care_plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه برنامه مراقبت')),
                ('category', models.CharField(choices=[('Nursing', 'پرستاری'), ('DischargePlan', 'برنامه ترخیص'), ('Nutrition', 'تغذیه'), ('Medication', 'دارویی'), ('Education', 'آموزشی'), ('Psychosocial', 'روانی-اجتماعی'), ('Rehabilitation', 'توانبخشی'), ('Other', 'سایر')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('goal', models.TextField(help_text='مثال: بیمار بتواند قند خون خود را مستقل چک کند', verbose_name='هدف')),
                ('intervention', models.TextField(help_text='مثال: آموزش استفاده از گلوکومتر', verbose_name='مداخله')),
                ('status', models.CharField(choices=[('Active', 'فعال'), ('Achieved', 'محقق شده'), ('Revised', 'تجدید نظر شده'), ('Canceled', 'لغو شده')], default='Active', max_length=20, verbose_name='وضعیت')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='تاریخ هدف')),
                ('evaluation_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ارزیابی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_care_plans', to='providers.provider', verbose_name='ایجاد کننده')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='encounters.encounter', verbose_name='ویزیت')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='clinical.problemlist', verbose_name='مشکل مرتبط')),
            ],
            options={
                'verbose_name': 'برنامه مراقبت',
                'verbose_name_plural': 'برنامه\u200cهای مراقبت',
                'ordering': ['-status', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CareTeam',
            fields=[
                ('care_team_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه تیم درمان')),
                ('role', models.CharField(choices=[('AttendingPhysician', 'پزشک معالج'), ('Consultant', 'پزشک مشاور'), ('PrimaryNurse', 'پرستار اصلی'), ('CaseManager', 'مدیر پرونده'), ('SocialWorker', 'مددکار اجتماعی'), ('Dietitian', 'متخصص تغذیه'), ('PhysicalTherapist', 'فیزیوتراپیست'), ('Pharmacist', 'داروساز'), ('Other', 'سایر')], max_length=50, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این فرد در حال حاضر فعال است؟', verbose_name='فعال')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اختصاص')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team_members', to='encounters.encounter', verbose_name='ویزیت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_teams', to='patients.patient', verbose_name='بیمار')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_team_assignments', to='providers.provider', verbose_name='عضو تیم درمان')),
            ],
            options={
                'verbose_name': 'عضو تیم درمان',
                'verbose_name_plural': 'تیم درمان',
                'ordering': ['is_active', '-assigned_date'],
            },
        ),
    ]
