# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه ویزیت')),
                ('encounter_date', models.DateTimeField(verbose_name='تاریخ و زمان ویزیت')),
                ('encounter_type', models.CharField(choices=[('Outpatient', 'سرپایی'), ('Inpatient', 'بستری'), ('Emergency', 'اورژانس'), ('Consultation', 'مشاوره')], max_length=50, verbose_name='نوع مراجعه')),
                ('chief_complaint', models.TextField(verbose_name='شکایت اصلی بیمار')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='بخش یا کلینیک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient', verbose_name='بیمار')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='providers.provider', verbose_name='پزشک معالج')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-encounter_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نوبت')),
                ('appointment_start_time', models.DateTimeField(verbose_name='زمان شروع نوبت')),
                ('appointment_end_time', models.DateTimeField(verbose_name='زمان پایان نوبت')),
                ('location', models.CharField(max_length=100, verbose_name='محل')),
                ('appointment_status', models.CharField(choices=[('Scheduled', 'زمان\u200cبندی شده'), ('Completed', 'انجام شده'), ('Canceled', 'لغو شده'), ('NoShow', 'عدم حضور'), ('Rescheduled', 'زمان\u200cبندی مجدد')], default='Scheduled', max_length=20, verbose_name='وضعیت نوبت')),
                ('reason_for_visit', models.TextField(blank=True, null=True, verbose_name='دلیل مراجعه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='بیمار')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='providers.provider', verbose_name='پزشک')),
                ('linked_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='encounters.encounter', verbose_name='ویزیت مرتبط')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['appointment_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه پذیرش')),
                ('admission_date', models.DateTimeField(verbose_name='تاریخ و زمان پذیرش')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ترخیص')),
                ('current_room', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اتاق فعلی')),
                ('current_bed', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره تخت فعلی')),
                ('admission_diagnosis', models.TextField(verbose_name='تشخیص زمان پذیرش')),
                ('discharge_diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص نهایی زمان ترخیص')),
                ('discharge_disposition', models.CharField(blank=True, choices=[('Home', 'مرخص به منزل'), ('Transferred', 'انتقال به مرکز دیگر'), ('Deceased', 'فوت'), ('Left_AMA', 'ترک با رضایت شخصی')], max_length=50, null=True, verbose_name='وضعیت ترخیص')),
                ('admitting_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='providers.provider', verbose_name='پزشک پذیرش دهنده')),
                ('discharge_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discharges', to='providers.provider', verbose_name='پزشک دستور دهنده ترخیص')),
                ('encounter', models.OneToOneField(limit_choices_to={'encounter_type': 'Inpatient'}, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='encounters.encounter', verbose_name='ویزیت')),
            ],
            options={
                'verbose_name': 'پذیرش',
                'verbose_name_plural': 'پذیرش\u200cها',
                'ordering': ['-admission_date'],
            },
        ),
    ]
