# Generated by Django 5.2.7 on 2025-10-22 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه کادر درمان')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='شماره نظام پزشکی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس کاری')),
                ('provider_type', models.CharField(choices=[('Doctor', 'پزشک'), ('Nurse', 'پرستار'), ('Technician', 'تکنسین'), ('Pharmacist', 'داروساز'), ('Radiologist', 'رادیولوژیست'), ('Pathologist', 'پاتولوژیست'), ('Anesthesiologist', 'متخصص بیهوشی'), ('Other', 'سایر')], max_length=50, verbose_name='نوع کادر درمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیوستن')),
            ],
            options={
                'verbose_name': 'کادر درمان',
                'verbose_name_plural': 'کادر درمان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
