# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('orders', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('lab_result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نتیجه آزمایش')),
                ('test_name', models.CharField(help_text='مثال: CBC, Blood Glucose, Creatinine', max_length=100, verbose_name='نام آزمایش')),
                ('result_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار نتیجه')),
                ('units', models.CharField(blank=True, help_text='مثال: mg/dL, mmol/L', max_length=20, null=True, verbose_name='واحد اندازه\u200cگیری')),
                ('reference_range', models.CharField(blank=True, help_text='مثال: 70-100', max_length=50, null=True, verbose_name='محدوده نرمال')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آماده شدن جواب')),
                ('status', models.CharField(choices=[('Pending', 'در انتظار'), ('InProgress', 'در حال انجام'), ('Complete', 'تکمیل شده'), ('Canceled', 'لغو شده')], default='Pending', max_length=20, verbose_name='وضعیت')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='غیر طبیعی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='encounters.encounter', verbose_name='ویزیت')),
                ('order', models.ForeignKey(limit_choices_to={'order_type': 'Lab'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='orders.order', verbose_name='دستور')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_lab_tests', to='providers.provider', verbose_name='انجام دهنده')),
            ],
            options={
                'verbose_name': 'نتیجه آزمایش',
                'verbose_name_plural': 'نتایج آزمایش\u200cها',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='MicrobiologyResult',
            fields=[
                ('micro_result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نتیجه میکروبیولوژی')),
                ('specimen_type', models.CharField(help_text='مثال: Blood Culture, Urine Culture, Wound Swab', max_length=100, verbose_name='نوع نمونه')),
                ('collection_date', models.DateTimeField(verbose_name='تاریخ نمونه\u200cگیری')),
                ('report_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ گزارش')),
                ('organism_name', models.CharField(blank=True, help_text='مثال: E. coli, No Growth After 48h', max_length=100, null=True, verbose_name='نام ارگانیسم')),
                ('sensitivity_data', models.JSONField(blank=True, help_text='نتایج حساسیت آنتی\u200cبیوتیکی به صورت JSON', null=True, verbose_name='داده\u200cهای آنتی\u200cبیوگرام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microbiology_results', to='encounters.encounter', verbose_name='ویزیت')),
                ('microbiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='microbiology_reports', to='providers.provider', verbose_name='میکروبیولوژیست')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microbiology_results', to='orders.order', verbose_name='دستور')),
            ],
            options={
                'verbose_name': 'نتیجه میکروبیولوژی',
                'verbose_name_plural': 'نتایج میکروبیولوژی',
                'ordering': ['-report_date'],
            },
        ),
    ]
