# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('orders', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نسخه')),
                ('medication_name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=100, verbose_name='دوز مصرف')),
                ('frequency', models.CharField(help_text='مثال: هر 8 ساعت، روزی 3 بار', max_length=100, verbose_name='تکرار مصرف')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان مصرف (روز)')),
                ('instructions', models.TextField(blank=True, help_text='مثال: بعد از غذا، با آب فراوان', null=True, verbose_name='دستورالعمل\u200cهای خاص')),
                ('refills', models.IntegerField(default=0, verbose_name='تعداد دفعات مجاز تکرار نسخه')),
                ('prescribed_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تجویز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='encounters.encounter', verbose_name='ویزیت')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_medications', to='providers.provider', verbose_name='پزشک تجویز کننده')),
            ],
            options={
                'verbose_name': 'نسخه دارو',
                'verbose_name_plural': 'نسخه\u200cهای دارو',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('med_admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه اجرای دارو')),
                ('medication_name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('administration_time', models.DateTimeField(verbose_name='زمان دادن دارو')),
                ('dosage_given', models.CharField(max_length=50, verbose_name='دوز داده شده')),
                ('route', models.CharField(choices=[('PO', 'خوراکی (Oral)'), ('IV', 'داخل وریدی (Intravenous)'), ('IM', 'داخل عضلانی (Intramuscular)'), ('SC', 'زیر جلدی (Subcutaneous)'), ('Topical', 'موضعی'), ('Inhalation', 'استنشاقی'), ('Rectal', 'رکتال'), ('Other', 'سایر')], max_length=20, verbose_name='مسیر دادن دارو')),
                ('site', models.CharField(blank=True, help_text='مثال: بازوی چپ، ران راست', max_length=50, null=True, verbose_name='محل تزریق')),
                ('patient_refusal', models.BooleanField(default=False, verbose_name='امتناع بیمار از مصرف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت پرستار')),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_medications', to='providers.provider', verbose_name='پرستار اجرا کننده')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='encounters.encounter', verbose_name='ویزیت')),
                ('order', models.ForeignKey(blank=True, limit_choices_to={'order_type': 'Medication'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='orders.order', verbose_name='دستور')),
            ],
            options={
                'verbose_name': 'اجرای دارو',
                'verbose_name_plural': 'اجرای داروها',
                'ordering': ['-administration_time'],
            },
        ),
    ]
