# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه تشخیص')),
                ('diagnosis_code', models.CharField(blank=True, help_text='کد استاندارد ICD-10', max_length=20, null=True, verbose_name='کد تشخیص')),
                ('diagnosis_description', models.TextField(verbose_name='شرح تشخیص')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تشخیص اصلی')),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تشخیص')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='providers.provider', verbose_name='تشخیص دهنده')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='encounters.encounter', verbose_name='ویزیت')),
            ],
            options={
                'verbose_name': 'تشخیص',
                'verbose_name_plural': 'تشخیص\u200cها',
                'ordering': ['-is_primary', '-diagnosis_date'],
            },
        ),
    ]
