# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه یادداشت')),
                ('note_type', models.CharField(choices=[('SOAP', 'شرح حال SOAP'), ('Progress', 'یادداشت پیشرفت'), ('Nursing', 'یادداشت پرستاری'), ('Discharge', 'خلاصه ترخیص'), ('Consultation', 'یادداشت مشاوره'), ('Admission', 'یادداشت پذیرش'), ('Operative', 'گزارش عمل'), ('Other', 'سایر')], max_length=50, verbose_name='نوع یادداشت')),
                ('note_text', models.TextField(help_text='متن کامل شرح حال، یادداشت یا گزارش', verbose_name='متن کامل یادداشت')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت یادداشت')),
                ('is_signed', models.BooleanField(default=False, verbose_name='امضا شده')),
                ('signed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان امضا')),
                ('amended', models.BooleanField(default=False, verbose_name='اصلاح شده')),
                ('amendment_text', models.TextField(blank=True, null=True, verbose_name='متن اصلاحیه')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='encounters.encounter', verbose_name='ویزیت')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='providers.provider', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'یادداشت بالینی',
                'verbose_name_plural': 'یادداشت\u200cهای بالینی',
                'ordering': ['-timestamp'],
            },
        ),
    ]
