# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('orders', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyReport',
            fields=[
                ('pathology_report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه گزارش پاتولوژی')),
                ('specimen_type', models.CharField(help_text='مثال: Biopsy, Left Breast Mass', max_length=100, verbose_name='نوع نمونه')),
                ('collection_date', models.DateTimeField(verbose_name='تاریخ نمونه\u200cبرداری')),
                ('report_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید گزارش')),
                ('macroscopic_description', models.TextField(blank=True, help_text='توصیف چیزی که با چشم دیده می\u200cشود', null=True, verbose_name='توصیف ماکروسکوپی')),
                ('microscopic_description', models.TextField(blank=True, help_text='توصیف نمونه تحت میکروسکوپ', null=True, verbose_name='توصیف میکروسکوپی')),
                ('final_diagnosis', models.TextField(blank=True, help_text='مثال: Invasive Ductal Carcinoma', null=True, verbose_name='تشخیص نهایی پاتولوژی')),
                ('additional_tests', models.TextField(blank=True, help_text='مثال: Immunohistochemistry, Molecular tests', null=True, verbose_name='تست\u200cهای اضافی')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_reports', to='encounters.encounter', verbose_name='ویزیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_reports', to='orders.order', verbose_name='دستور')),
                ('pathologist', models.ForeignKey(limit_choices_to={'provider_type': 'Pathologist'}, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_reports', to='providers.provider', verbose_name='پاتولوژیست')),
            ],
            options={
                'verbose_name': 'گزارش پاتولوژی',
                'verbose_name_plural': 'گزارش\u200cهای پاتولوژی',
                'ordering': ['-report_date'],
            },
        ),
    ]
