# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه پروسیجر')),
                ('procedure_name', models.CharField(help_text='مثال: Appendectomy, Bronchoscopy', max_length=300, verbose_name='نام عمل')),
                ('procedure_code', models.CharField(blank=True, help_text='کد CPT یا ICD-10-PCS', max_length=50, null=True, verbose_name='کد استاندارد عمل')),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ و زمان شروع عمل')),
                ('procedure_report', models.TextField(blank=True, null=True, verbose_name='گزارش کامل عمل')),
                ('complications', models.TextField(blank=True, null=True, verbose_name='عوارض حین یا پس از عمل')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان عمل (دقیقه)')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='اورژانسی')),
                ('anesthesiologist', models.ForeignKey(blank=True, limit_choices_to={'provider_type': 'Anesthesiologist'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anesthesia_procedures', to='providers.provider', verbose_name='متخصص بیهوشی')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='encounters.encounter', verbose_name='ویزیت')),
                ('order', models.ForeignKey(blank=True, limit_choices_to={'order_type': 'Procedure'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='orders.order', verbose_name='دستور')),
                ('primary_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_surgeries', to='providers.provider', verbose_name='جراح اصلی')),
            ],
            options={
                'verbose_name': 'پروسیجر/عمل',
                'verbose_name_plural': 'پروسیجرها و اعمال',
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('consent_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه رضایت\u200cنامه')),
                ('consent_type', models.CharField(help_text='مثال: General Treatment, Surgery, Blood Transfusion', max_length=100, verbose_name='نوع رضایت\u200cنامه')),
                ('consent_status', models.CharField(choices=[('Signed', 'امضا شده'), ('Revoked', 'لغو شده'), ('Pending', 'در انتظار')], default='Pending', max_length=20, verbose_name='وضعیت رضایت\u200cنامه')),
                ('sign_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('scanned_form_path', models.FileField(blank=True, null=True, upload_to='consent_forms/', verbose_name='فایل اسکن شده رضایت\u200cنامه')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='encounters.encounter', verbose_name='ویزیت مرتبط')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='patients.patient', verbose_name='بیمار')),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnessed_consents', to='providers.provider', verbose_name='شاهد امضا')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='procedures.procedure', verbose_name='پروسیجر مرتبط')),
            ],
            options={
                'verbose_name': 'رضایت\u200cنامه',
                'verbose_name_plural': 'رضایت\u200cنامه\u200cها',
                'ordering': ['-sign_timestamp'],
            },
        ),
    ]
