# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('vital_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه علائم حیاتی')),
                ('timestamp', models.DateTimeField(verbose_name='زمان ثبت')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='فشار خون سیستولیک (بالا)')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='فشار خون دیاستولیک (پایین)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='ضربان قلب')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دمای بدن')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='نرخ تنفس')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='اشباع اکسیژن (SpO2)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('height_cm', models.IntegerField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='encounters.encounter', verbose_name='ویزیت')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vitals', to='providers.provider', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'علائم حیاتی',
                'verbose_name_plural': 'علائم حیاتی',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlowsheetData',
            fields=[
                ('flowsheet_entry_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه فلوشیت')),
                ('timestamp', models.DateTimeField(verbose_name='زمان ثبت')),
                ('flowsheet_item_name', models.CharField(help_text='مثال: HeartRate, PainScore, UrineOutput, GCS_Total', max_length=100, verbose_name='نام آیتم')),
                ('item_value', models.CharField(max_length=100, verbose_name='مقدار آیتم')),
                ('units', models.CharField(blank=True, help_text='مثال: bpm, mL, 1-10', max_length=20, null=True, verbose_name='واحد')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowsheet_data', to='encounters.encounter', verbose_name='ویزیت')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_flowsheets', to='providers.provider', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'داده فلوشیت',
                'verbose_name_plural': 'داده\u200cهای فلوشیت',
                'ordering': ['-timestamp', 'flowsheet_item_name'],
                'indexes': [models.Index(fields=['encounter', 'flowsheet_item_name', '-timestamp'], name='vitals_flow_encount_ff089e_idx')],
            },
        ),
    ]
