# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه بیمار')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن'), ('Other', 'سایر')], max_length=10, verbose_name='جنسیت')),
                ('primary_phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن اصلی')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس منزل')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='نام مخاطب اضطراری')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='تلفن مخاطب اضطراری')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='گروه خونی')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه بیمه')),
                ('provider_name', models.CharField(max_length=100, verbose_name='نام شرکت بیمه')),
                ('policy_number', models.CharField(max_length=100, verbose_name='شماره بیمه\u200cنامه')),
                ('group_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره گروه')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('insurance_type', models.CharField(choices=[('Primary', 'پایه'), ('Supplementary', 'تکمیلی')], max_length=20, verbose_name='نوع بیمه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'بیمه',
                'verbose_name_plural': 'بیمه\u200cها',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
