# Generated by Django 5.2.7 on 2025-10-22 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه دستور')),
                ('order_type', models.CharField(choices=[('Medication', 'دارو'), ('Lab', 'آزمایش'), ('Imaging', 'تصویربرداری'), ('Procedure', 'پروسیجر'), ('Consult', 'مشاوره'), ('Diet', 'رژیم غذایی'), ('Other', 'سایر')], max_length=50, verbose_name='نوع دستور')),
                ('order_description', models.TextField(verbose_name='شرح دستور')),
                ('order_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان صدور دستور')),
                ('order_status', models.CharField(choices=[('Pending', 'در انتظار'), ('InProgress', 'در حال انجام'), ('Complete', 'انجام شده'), ('Canceled', 'لغو شده'), ('Held', 'متوقف شده')], default='Pending', max_length=20, verbose_name='وضعیت دستور')),
                ('priority', models.CharField(choices=[('STAT', 'فوری'), ('ASAP', 'در اسرع وقت'), ('Routine', 'معمولی')], default='Routine', max_length=10, verbose_name='اولویت')),
                ('reason_for_order', models.TextField(blank=True, null=True, verbose_name='دلیل دستور')),
                ('completed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='encounters.encounter', verbose_name='ویزیت')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.provider', verbose_name='دستور دهنده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'دستور پزشکی',
                'verbose_name_plural': 'دستورات پزشکی',
                'ordering': ['-order_timestamp'],
                'indexes': [models.Index(fields=['order_status', '-order_timestamp'], name='orders_orde_order_s_d49409_idx'), models.Index(fields=['priority', '-order_timestamp'], name='orders_orde_priorit_bf906d_idx')],
            },
        ),
    ]
